create table BlogEntry
(
    id        int auto_increment
        primary key,
    authorId  int                                 not null,
    created   timestamp default CURRENT_TIMESTAMP not null,
    modified  timestamp                           null,
    contentId int                                 not null,
    title     varchar(255)                        not null,
    constraint BlogEntry_ibfk_1
        foreign key (authorId) references Users (id),
    constraint BlogEntry_ibfk_2
        foreign key (contentId) references BlogEntryContent (id)
);

create index authorId
    on BlogEntry (authorId);

create index contentId
    on BlogEntry (contentId);

INSERT INTO MyBlog.BlogEntry (id, authorId, created, modified, contentId, title) VALUES (2, 1, '2019-04-17 20:33:22', null, 1, 'Lorem ipsum ftw!');
INSERT INTO MyBlog.BlogEntry (id, authorId, created, modified, contentId, title) VALUES (3, 1, '2019-04-18 07:54:25', '2019-04-19 20:02:13', 2, 'This just in!');
INSERT INTO MyBlog.BlogEntry (id, authorId, created, modified, contentId, title) VALUES (4, 1, '2019-04-18 07:55:04', null, 3, 'And now, something completely different!');
INSERT INTO MyBlog.BlogEntry (id, authorId, created, modified, contentId, title) VALUES (6, 1, '2019-04-19 19:57:31', '2019-04-19 20:01:35', 5, 'Once upon a time');
INSERT INTO MyBlog.BlogEntry (id, authorId, created, modified, contentId, title) VALUES (7, 1, '2019-04-19 20:00:38', null, 6, 'And another one');
INSERT INTO MyBlog.BlogEntry (id, authorId, created, modified, contentId, title) VALUES (8, 1, '2019-04-25 14:43:52', '2019-04-25 14:44:20', 7, 'And a new one for a new day');
create table BlogEntryContent
(
    id      int auto_increment
        primary key,
    content longtext null
);

INSERT INTO MyBlog.BlogEntryContent (id, content) VALUES (1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam tristique magna sit amet ultricies ornare. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur euismod sem velit, nec tempor dui lacinia sed. In hac habitasse platea dictumst. Duis ac auctor libero. Aenean posuere neque tortor, blandit fermentum diam interdum at. Suspendisse posuere porttitor erat et consequat. Quisque vel dolor cursus, ornare mi sit amet, faucibus purus. Aenean in velit nisl. Aliquam condimentum nunc eget eros auctor placerat. Donec condimentum aliquam semper. Nunc at nisi ac dui ornare placerat at nec eros. Aliquam enim nisl, aliquam quis nunc quis, ornare bibendum felis. Ut condimentum aliquam urna in tempus. Nam non neque aliquam, ultrices felis ac, sodales justo. Ut eget mi mollis dolor luctus rhoncus nec sit amet dolor.
Aenean laoreet et enim eget feugiat. Donec volutpat tortor eu neque ultrices fringilla. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Praesent efficitur nibh justo, non ullamcorper velit fermentum varius. Mauris cursus felis convallis ligula posuere, nec imperdiet arcu tincidunt. Duis nec velit eget nunc porttitor dictum non vitae elit. Morbi cursus massa ac erat pretium, id porta sem laoreet. Aliquam erat volutpat. Mauris varius sagittis tempor. Proin viverra magna in est pulvinar imperdiet. Fusce suscipit ullamcorper mattis. Phasellus ultrices dolor eget tellus lobortis, nec sagittis urna maximus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
Sed ultrices vestibulum justo, sed tempus neque. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Praesent ultricies urna mollis, fermentum dolor vitae, iaculis tortor. Fusce porta lorem at ex mattis, ut ultrices mauris euismod. Proin laoreet placerat aliquet. Nunc nec purus elit. Donec blandit, elit eu egestas lobortis, odio ipsum dapibus nunc, et placerat ligula magna ac diam. Nullam scelerisque tortor nec nulla aliquet luctus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce cursus, eros maximus placerat semper, dolor leo posuere arcu, sed scelerisque eros orci id est. Sed non urna id nibh malesuada tempor. Duis id dui tincidunt magna venenatis mollis. Etiam dui ex, ultrices vitae ornare sit amet, hendrerit sed sapien. Quisque euismod ipsum consectetur neque maximus aliquam. Mauris mollis felis vel gravida egestas.
Aenean id facilisis est. Cras quis ipsum varius, mollis tellus at, volutpat quam. Maecenas arcu ipsum, pharetra a blandit auctor, vehicula eu ipsum. Aenean mattis urna ac iaculis faucibus. Proin massa enim, finibus molestie erat ac, sagittis rhoncus nisi. Pellentesque faucibus luctus lectus vitae placerat. Nullam eget euismod augue. Donec orci metus, congue et egestas vitae, varius nec est.
Nam sit amet arcu ipsum. Pellentesque interdum laoreet urna, eu elementum lacus dignissim vel. Donec sapien nisi, ultrices accumsan turpis ac, tristique iaculis arcu. Praesent ut lectus in odio luctus fringilla sit amet at sem. Pellentesque faucibus vulputate interdum. Mauris efficitur nibh quis sapien faucibus auctor. Donec lobortis, lectus ut vestibulum lobortis, mi dolor laoreet nibh, vitae eleifend justo justo in arcu. Quisque nec ante tincidunt ipsum pulvinar cursus sit amet sit amet nulla. Aenean vestibulum eros in arcu egestas finibus. Phasellus quis metus quis turpis euismod rutrum at ac magna. Phasellus commodo tincidunt ligula, non ornare ex tempor tincidunt. ');
INSERT INTO MyBlog.BlogEntryContent (id, content) VALUES (2, '
Fusce interdum felis sit amet ipsum auctor consequat. Nulla purus dui, suscipit et tincidunt vel, egestas vel nisi. In elit lectus, fringilla in suscipit vel, dapibus et mauris. Pellentesque consectetur mattis felis, a lobortis nisl lacinia quis. Integer sed nibh non elit condimentum cursus. Ut dignissim purus mollis nibh blandit hendrerit. Donec condimentum volutpat elit eget fermentum.

Aenean metus est, ultrices ac viverra a, convallis nec orci. Integer cursus, massa eu venenatis suscipit, odio nulla feugiat risus, ut mollis mi quam at felis. Donec accumsan iaculis nisl, et sodales risus. Donec sodales mattis laoreet. Duis tincidunt ac quam id ultrices. In sed semper justo, vel feugiat lorem. Integer commodo egestas odio sit amet congue. Ut et egestas erat.

Maecenas nunc lorem, tincidunt vitae scelerisque non, tempor id massa. Mauris eu justo lorem. Morbi sed faucibus felis, sit amet auctor nisl. Donec semper egestas felis. Etiam lobortis luctus pellentesque. Nullam lobortis luctus nibh, id imperdiet augue consequat a. Aenean ullamcorper tempus suscipit. Proin commodo felis ipsum, a mollis velit mattis a. Fusce malesuada vitae purus sed vulputate. Aenean fermentum dolor quis eros feugiat, sed tincidunt mauris egestas. Sed tincidunt id elit non maximus. Morbi condimentum ornare ante, vel volutpat nisi aliquet vitae.

Mauris ex diam, vestibulum aliquam libero ut, vulputate convallis est. Praesent vitae nunc eget velit iaculis euismod non id sapien. Aenean eget molestie nibh. Nunc mauris urna, mollis sed arcu ut, sagittis iaculis risus. Nullam id nibh accumsan, rhoncus tellus vitae, mattis odio. Sed mattis metus ut eros porta, nec dignissim orci placerat. Aenean velit eros, suscipit nec diam quis, posuere lacinia justo. Nulla ultricies tortor vel faucibus finibus. Etiam ac rhoncus enim. Suspendisse ullamcorper eget neque et rhoncus.

Maecenas ultrices sollicitudin sem sit amet porta. In hac habitasse platea dictumst. Fusce efficitur iaculis turpis non posuere. Curabitur malesuada risus risus, non fringilla tortor egestas vitae. Mauris id velit lorem. Donec fringilla convallis tempus. Phasellus sit amet ipsum eu mi auctor elementum. Donec ante lectus, tempus nec dui ac, viverra venenatis ipsum. Pellentesque quis libero ac lorem vehicula molestie vel a mauris. Phasellus cursus metus vel velit consequat, a malesuada libero congue.

In imperdiet, risus non interdum sagittis, odio turpis porttitor massa, ut ullamcorper libero lectus quis tortor. Nulla in eleifend enim. Nullam tempus nulla nec sem aliquet, ut faucibus lorem feugiat. Sed cursus blandit mi, sit amet consequat lorem interdum nec. Ut fermentum varius faucibus. Suspendisse sit amet diam eget erat pellentesque aliquet sit amet non sapien. In pharetra urna et convallis sagittis. Donec iaculis, felis a luctus bibendum, ipsum sapien blandit ligula, eu vehicula ipsum orci nec est.

Aenean non hendrerit ante. Nullam odio ipsum, congue vitae massa non, eleifend sagittis metus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce euismod arcu a elit venenatis pharetra. Donec ornare erat augue, at condimentum odio mattis ultrices. Donec dictum ornare nisi id mollis. Nunc sodales rutrum nisl eget blandit. Sed placerat odio eu mi bibendum facilisis. Nulla sem mauris, dignissim in lectus vel, vestibulum tincidunt est. Etiam in lorem felis. Quisque in felis vel erat gravida sodales. Proin venenatis tempor nulla sed molestie.

Donec pretium eu leo non condimentum. Aliquam at tortor gravida, rhoncus felis nec, laoreet elit. Aenean iaculis a dolor et volutpat. Vivamus ut metus a sem blandit gravida et sit amet turpis. In lobortis purus sapien, a vulputate ligula gravida quis. Nunc non diam sem. Nullam sed consectetur ex. Etiam nisl nunc, tempor a ultrices eu, tempor id nisl. Proin dapibus quam nulla, sed viverra libero convallis et. Aliquam placerat nunc vitae luctus venenatis. Donec sodales, risus a eleifend mollis, orci felis iaculis augue, sit amet laoreet ante libero quis orci. Donec mollis risus et quam sagittis laoreet. Duis sed consectetur nisl. Ut in sem quis magna varius sodales. Duis in tincidunt lacus, pretium bibendum lectus.

Pellentesque at velit quis neque tincidunt cursus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus tempor est sit amet purus ultricies, sed facilisis magna efficitur. Fusce at mi tortor. Ut ut dolor tortor. Quisque sollicitudin eu velit sit amet lobortis. Vestibulum non volutpat tortor, at pulvinar dui. Maecenas et ex libero. Etiam molestie, ex at cursus laoreet, libero libero mollis dolor, eu pulvinar enim dui at metus.

Cras nec orci vel massa tristique auctor. Nunc consequat eu neque eu venenatis. Vestibulum metus urna, gravida vel malesuada vitae, fringilla a sem. Aliquam erat volutpat. Maecenas ornare eu enim euismod sagittis. Nunc mollis sem sed dolor finibus viverra. Vivamus sit amet quam est. Sed pulvinar tellus ac lectus efficitur mollis. Morbi elementum fermentum tempus. Maecenas volutpat nulla metus, ac porta ipsum molestie feugiat. Morbi cursus pretium lectus sit amet sollicitudin. ');
INSERT INTO MyBlog.BlogEntryContent (id, content) VALUES (3, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam tristique magna sit amet ultricies ornare. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur euismod sem velit, nec tempor dui lacinia sed. In hac habitasse platea dictumst. Duis ac auctor libero. Aenean posuere neque tortor, blandit fermentum diam interdum at. Suspendisse posuere porttitor erat et consequat. Quisque vel dolor cursus, ornare mi sit amet, faucibus purus. Aenean in velit nisl. Aliquam condimentum nunc eget eros auctor placerat. Donec condimentum aliquam semper. Nunc at nisi ac dui ornare placerat at nec eros. Aliquam enim nisl, aliquam quis nunc quis, ornare bibendum felis. Ut condimentum aliquam urna in tempus. Nam non neque aliquam, ultrices felis ac, sodales justo. Ut eget mi mollis dolor luctus rhoncus nec sit amet dolor.
Aenean laoreet et enim eget feugiat. Donec volutpat tortor eu neque ultrices fringilla. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Praesent efficitur nibh justo, non ullamcorper velit fermentum varius. Mauris cursus felis convallis ligula posuere, nec imperdiet arcu tincidunt. Duis nec velit eget nunc porttitor dictum non vitae elit. Morbi cursus massa ac erat pretium, id porta sem laoreet. Aliquam erat volutpat. Mauris varius sagittis tempor. Proin viverra magna in est pulvinar imperdiet. Fusce suscipit ullamcorper mattis. Phasellus ultrices dolor eget tellus lobortis, nec sagittis urna maximus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
Sed ultrices vestibulum justo, sed tempus neque. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Praesent ultricies urna mollis, fermentum dolor vitae, iaculis tortor. Fusce porta lorem at ex mattis, ut ultrices mauris euismod. Proin laoreet placerat aliquet. Nunc nec purus elit. Donec blandit, elit eu egestas lobortis, odio ipsum dapibus nunc, et placerat ligula magna ac diam. Nullam scelerisque tortor nec nulla aliquet luctus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce cursus, eros maximus placerat semper, dolor leo posuere arcu, sed scelerisque eros orci id est. Sed non urna id nibh malesuada tempor. Duis id dui tincidunt magna venenatis mollis. Etiam dui ex, ultrices vitae ornare sit amet, hendrerit sed sapien. Quisque euismod ipsum consectetur neque maximus aliquam. Mauris mollis felis vel gravida egestas.
Aenean id facilisis est. Cras quis ipsum varius, mollis tellus at, volutpat quam. Maecenas arcu ipsum, pharetra a blandit auctor, vehicula eu ipsum. Aenean mattis urna ac iaculis faucibus. Proin massa enim, finibus molestie erat ac, sagittis rhoncus nisi. Pellentesque faucibus luctus lectus vitae placerat. Nullam eget euismod augue. Donec orci metus, congue et egestas vitae, varius nec est.
Nam sit amet arcu ipsum. Pellentesque interdum laoreet urna, eu elementum lacus dignissim vel. Donec sapien nisi, ultrices accumsan turpis ac, tristique iaculis arcu. Praesent ut lectus in odio luctus fringilla sit amet at sem. Pellentesque faucibus vulputate interdum. Mauris efficitur nibh quis sapien faucibus auctor. Donec lobortis, lectus ut vestibulum lobortis, mi dolor laoreet nibh, vitae eleifend justo justo in arcu. Quisque nec ante tincidunt ipsum pulvinar cursus sit amet sit amet nulla. Aenean vestibulum eros in arcu egestas finibus. Phasellus quis metus quis turpis euismod rutrum at ac magna. Phasellus commodo tincidunt ligula, non ornare ex tempor tincidunt. ');
INSERT INTO MyBlog.BlogEntryContent (id, content) VALUES (4, 'This is a rather short blog post. What a waste of screen real estate, innit?');
INSERT INTO MyBlog.BlogEntryContent (id, content) VALUES (5, '

Nam sodales lorem felis, et iaculis orci tempor eu. Nunc mi nisi, consectetur id pretium a, euismod ac dui. Integer iaculis lorem nulla, eu laoreet ipsum molestie at. Suspendisse eu vehicula neque. Pellentesque cursus maximus lacus condimentum volutpat. Aenean id felis urna. Fusce varius diam non ipsum eleifend rutrum. Curabitur eget ligula vel tortor ullamcorper eleifend at sit amet nulla. Proin pharetra mollis nulla id elementum. Sed mollis eros vel ligula dictum, nec dapibus orci aliquet. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur laoreet mauris ac ligula viverra feugiat. Proin turpis augue, aliquam sed risus vitae, semper efficitur quam.

Morbi placerat lacinia turpis, lobortis cursus mauris commodo vel. Vestibulum a odio ac ligula hendrerit tempor bibendum at lorem. Phasellus sem enim, aliquam aliquam euismod facilisis, condimentum et orci. In sollicitudin in dolor vitae lobortis. Suspendisse rhoncus mi ut ex fermentum fermentum. In tristique pretium nisl, ac euismod lorem rhoncus quis. Aenean faucibus cursus auctor. Ut gravida, nisl non tincidunt lacinia, risus ante aliquam arcu, non blandit sapien lorem vel sem. Maecenas porta pretium turpis, luctus tempor augue auctor in. Integer quis enim nec massa fermentum porttitor. Morbi consequat nulla eu sollicitudin viverra. Etiam et varius urna.

Aliquam erat volutpat. Vestibulum congue tempor nisl, vitae tristique nunc mollis non. Interdum et malesuada fames ac ante ipsum primis in faucibus. Integer non libero leo. In vitae eros vel lorem feugiat bibendum. Mauris auctor, urna lobortis convallis porta, metus tellus convallis sapien, euismod commodo odio tortor sit amet elit. Fusce ut luctus leo. Ut placerat nec tortor at hendrerit. Donec aliquam eleifend leo id condimentum. In et mi ac odio lacinia luctus vel eget neque.

Praesent vel commodo quam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla at lorem nec felis ultrices eleifend. Donec ultricies ante sed ex egestas consequat. Cras rutrum ex sit amet diam aliquet, sed venenatis velit eleifend. Nulla condimentum nisi id elit tincidunt, vel porta lorem luctus. Fusce urna felis, iaculis sed elit a, accumsan tempor lacus. Maecenas bibendum luctus dolor, pharetra consequat sapien placerat sit amet.

Nam malesuada venenatis lacus, a bibendum nisi commodo auctor. Curabitur a eros tortor. Mauris sed vulputate quam. Morbi interdum imperdiet ipsum, eget euismod ipsum faucibus a. Praesent tincidunt sem at mauris posuere luctus nec vel mauris. Mauris vitae posuere massa, at vehicula diam. Duis nunc magna, convallis fringilla posuere et, dignissim at orci. Ut a varius augue. In ut fermentum magna. Morbi quis bibendum arcu, id finibus diam. Sed interdum ex nulla, eu volutpat neque gravida et. Duis tempor bibendum nisi, ac hendrerit augue tempus ornare. Nullam pellentesque lorem quam, at dictum risus dignissim non. Quisque dignissim suscipit vestibulum. Donec vehicula suscipit quam, in blandit libero faucibus nec. Quisque convallis elit at orci accumsan, nec dictum libero volutpat.

Phasellus venenatis, magna a lacinia lacinia, leo ex molestie massa, non luctus nisl nisi ac ex. Donec dapibus nec augue sed sagittis. Nulla mattis blandit dictum. Sed sit amet quam sed mauris iaculis placerat eget vitae eros. Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiam dignissim, ligula ut pretium tincidunt, dolor ex sagittis lectus, at ullamcorper justo lorem in orci. Donec auctor congue nulla vestibulum pretium. Suspendisse pretium metus sit amet sapien semper, et condimentum lacus accumsan. Sed porttitor ante a rhoncus varius. Fusce tempor mattis ante in tempor. Vestibulum interdum, sem eget dictum euismod, ligula velit ultrices neque, et tempor velit magna eget ante. Nullam in lorem pretium, cursus turpis at, consectetur lacus. Aliquam eget nulla consectetur, laoreet libero sed, mattis mi. Donec dapibus vehicula arcu, ac congue diam gravida ac. Aliquam mauris massa, posuere non porta et, tempor ac felis.

Proin tellus lorem, iaculis et risus accumsan, malesuada ornare justo. Nullam sodales, enim eu placerat sollicitudin, neque metus malesuada sem, in pretium libero turpis in lectus. Curabitur bibendum ante in augue convallis porta. Morbi mollis, ex ut sagittis maximus, mi felis pellentesque tellus, vel tincidunt lorem velit vel est. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas lobortis dictum quam, scelerisque aliquam eros. Ut et libero sed enim laoreet aliquam id quis leo. Sed volutpat arcu quis augue consequat, et pulvinar felis lobortis. Suspendisse vel ipsum lectus. Curabitur porttitor felis velit. Pellentesque libero sem, vestibulum quis velit sit amet, scelerisque convallis quam. Vivamus mollis fermentum elementum. Sed lacus mi, finibus a imperdiet ut, convallis dapibus quam.

Proin mi nunc, cursus sed metus et, ultrices mollis lacus. Sed et sollicitudin felis. Curabitur nec lobortis odio. Quisque malesuada ornare velit nec feugiat. Quisque quis libero scelerisque, malesuada magna vitae, facilisis lorem. Praesent sed dui interdum, facilisis eros sed, posuere risus. Integer accumsan ipsum eleifend laoreet tincidunt. Proin gravida mi vel turpis dapibus pretium. Morbi quis auctor felis. In hac habitasse platea dictumst. Nam porttitor odio felis, euismod rhoncus nibh feugiat quis. Pellentesque venenatis eget orci vel egestas. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

Curabitur hendrerit vel arcu ac molestie. Nullam condimentum mauris eget mollis interdum. Etiam dictum sit amet neque eu volutpat. Nulla non nulla non leo interdum ultricies id sit amet sem. Aliquam fermentum, turpis a varius viverra, felis odio cursus nulla, quis auctor neque ante vel neque. Sed auctor eleifend ornare. Sed et elit leo.

Sed convallis velit eget elit tempor imperdiet. Suspendisse vel massa nec est ornare fringilla. Aenean volutpat a augue ut posuere. Ut eros lorem, placerat quis augue et, sollicitudin ultricies mi. Morbi non arcu ultricies tellus sodales varius. Nunc sed aliquam diam. Aliquam in congue purus, mollis scelerisque mauris. Proin lobortis massa id malesuada ornare. ');
INSERT INTO MyBlog.BlogEntryContent (id, content) VALUES (6, '

Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut sagittis enim elit, ut vulputate ligula elementum sed. Nam at nulla non odio dignissim vulputate. Duis quis nulla accumsan, semper neque non, porta lorem. Cras in dui eu metus varius pharetra non nec quam. Etiam quis sem lacus. Sed eu nibh magna. Proin hendrerit neque sit amet neque fringilla, in convallis ipsum interdum.

Nullam laoreet iaculis sapien, consectetur sagittis nunc hendrerit ut. Aliquam erat volutpat. Nam non tempor elit, sit amet interdum mi. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse suscipit, purus sit amet hendrerit varius, felis nulla sollicitudin erat, quis volutpat mi tellus in neque. Morbi in faucibus nisl. Ut condimentum accumsan massa, sed bibendum nibh venenatis vitae. Etiam euismod a ex id placerat. Nunc cursus ut quam vel consequat. Morbi in velit at tortor interdum pretium ac eget metus. Duis semper dolor id sapien imperdiet, a tincidunt felis iaculis. Nunc facilisis velit justo, in rutrum ex semper a. Maecenas luctus imperdiet erat vitae viverra. Curabitur augue leo, pharetra quis est in, efficitur accumsan dolor.

Integer vehicula lectus eu dapibus imperdiet. Nullam commodo mollis erat, varius accumsan lacus vestibulum vel. Nunc accumsan mi quis sollicitudin elementum. Fusce lobortis rutrum semper. Aliquam accumsan congue elementum. Fusce eget velit fringilla, accumsan elit eu, posuere felis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.

Nulla sagittis ultrices nisl, ut faucibus mi malesuada eget. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce bibendum mauris at est iaculis, vel feugiat felis iaculis. Etiam sit amet venenatis nulla, sed luctus risus. Quisque mattis ornare finibus. Nulla ultricies mauris massa, vel ullamcorper est maximus sed. Vestibulum ornare, nulla eu hendrerit dignissim, sapien risus hendrerit risus, eget cursus mauris erat eu sapien. Morbi lacinia erat quis vulputate tincidunt. Nam vitae sagittis lacus. Phasellus ornare facilisis mattis.

Suspendisse aliquam turpis finibus urna elementum varius. Aenean fringilla lacus at quam tincidunt, a tristique nisl euismod. Nunc interdum odio tortor, eu ultricies quam convallis ut. Sed interdum feugiat quam eu hendrerit. Nullam et finibus augue, eget pulvinar est. Nam mi ligula, lobortis sit amet ex quis, venenatis vestibulum libero. Duis mauris quam, feugiat a tempor vitae, imperdiet et lorem. Aliquam venenatis malesuada egestas. Praesent vel maximus ex. In metus velit, blandit in purus sed, congue consequat erat. Pellentesque at odio sed mauris imperdiet rutrum sit amet vitae dui. Curabitur pellentesque fringilla lectus vitae vulputate. Proin ac ante at massa sodales scelerisque. Curabitur ut mi at libero rhoncus pharetra sit amet sagittis ex. Fusce consequat rhoncus purus sed feugiat. Nam vulputate eros ante, non tristique ex mollis vitae. ');
INSERT INTO MyBlog.BlogEntryContent (id, content) VALUES (7, 'Nam feugiat efficitur nunc, non luctus ex scelerisque vitae. Aliquam metus purus, sagittis id ex id, venenatis auctor nisl. Vivamus ac erat ut augue imperdiet suscipit. Maecenas id sollicitudin purus. Quisque egestas diam quis justo molestie blandit at eget nibh. Quisque ac augue aliquet, egestas lacus vel, rutrum nisl. Sed pretium id ligula eget consequat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam convallis purus magna, sit amet lacinia ipsum sollicitudin sed. Aenean blandit, mi ut accumsan scelerisque, ipsum orci vestibulum nibh, ac porttitor ante ex eget justo. Suspendisse dignissim risus gravida arcu vestibulum, sit amet sollicitudin lectus lacinia.

Donec in sem in arcu faucibus tincidunt eu suscipit velit. Duis euismod vitae risus id congue. Fusce lobortis, sapien lacinia bibendum suscipit, felis nibh rhoncus justo, at dapibus tellus nisi in elit. Quisque augue ex, blandit ultrices malesuada id, euismod ut velit. Suspendisse efficitur lacus non maximus aliquet. In suscipit sit amet magna eu auctor. Vivamus mattis diam quis tortor faucibus, viverra vulputate est faucibus.

Quisque id ante pellentesque, consectetur nisl egestas, convallis ipsum. Maecenas non suscipit leo, at viverra leo. Sed tellus augue, aliquam ut facilisis eu, posuere ut purus. Suspendisse non congue est. Vivamus tortor neque, gravida at libero vel, egestas dapibus turpis. Nullam ornare justo ac eleifend ullamcorper. Proin id lacus mi. Vestibulum posuere aliquet sapien, eget blandit lorem lobortis et. Etiam in lacus eu tortor consequat feugiat. Pellentesque non quam vestibulum, efficitur dui sed, aliquet urna. Nunc lacinia erat ut diam molestie, eget feugiat est pharetra. Proin blandit ante id sem auctor, vitae placerat arcu ornare.

Phasellus sit amet cursus est. Aenean et pulvinar sapien. Nullam mauris risus, laoreet at elementum eget, pellentesque at sem. Curabitur sit amet ipsum nec lectus interdum pulvinar. Vestibulum et dui vitae orci elementum aliquam ut ac sapien. Ut gravida massa et dolor rhoncus bibendum. Sed at purus eleifend, egestas leo sit amet, fringilla ex. Duis ante turpis, eleifend id nibh pulvinar, volutpat blandit velit. Etiam ac massa nec lorem convallis mattis. Morbi efficitur magna nisi, vitae venenatis ex lacinia sit amet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla nunc erat, porta sit amet pulvinar sit amet, interdum sed dolor. Aenean vitae nulla vel enim sollicitudin varius. Suspendisse hendrerit felis erat, vitae sagittis ante volutpat ut. Vivamus pulvinar quam vel egestas pulvinar. Vestibulum tellus dui, varius sed blandit efficitur, varius a tellus.

Nunc commodo semper erat eget hendrerit. Nam dignissim neque arcu, vitae dictum turpis faucibus vitae. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas tincidunt semper diam, vitae luctus turpis volutpat sed. Etiam ut leo eu lorem sagittis porta eu id lacus. Aliquam erat volutpat. Nulla in nulla a tellus mollis malesuada. Quisque sed facilisis neque. Aenean venenatis mauris neque, sed sagittis ligula rhoncus non. Suspendisse vulputate velit mi, at efficitur leo semper sed. Curabitur dapibus eleifend nunc, vel egestas magna dignissim vel. Sed ac massa ut metus commodo gravida. Aenean convallis magna sit amet dignissim dignissim. Ut nec molestie ligula. Donec vitae eleifend orci, sodales pretium diam. Vestibulum tempus mollis enim non accumsan.

Morbi sed consectetur felis. In mollis egestas purus ut dictum. Morbi et lorem ut erat pellentesque vulputate id eget ex. Praesent eleifend urna sit amet libero pharetra viverra. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin maximus urna mi, et tempus leo mattis id. Cras tristique, nunc malesuada dictum facilisis, felis velit ornare lorem, quis pharetra quam purus non mauris. Proin dapibus turpis vulputate, mattis dui sit amet, pharetra libero. Donec pretium, elit nec fringilla ultricies, orci ipsum luctus urna, non tincidunt ex odio at lectus. Proin et pulvinar risus. Vestibulum ante ligula, consectetur volutpat arcu sed, bibendum sagittis est. Nullam porttitor, nisl eget sollicitudin tincidunt, ex eros ultricies ex, at viverra ante lacus nec purus. Nulla cursus laoreet tortor vel suscipit.

Integer tristique a ligula eu sodales. Etiam nisi diam, rutrum et sagittis lobortis, bibendum id quam. Maecenas pretium dolor quis sollicitudin consequat. Cras pulvinar ex ut placerat ultricies. Aliquam vehicula massa ut tellus efficitur dapibus. Aliquam erat volutpat. Etiam in malesuada quam.

Pellentesque non est in nibh dapibus placerat id sit amet est. Morbi eget placerat ex, sit amet tempus erat. Vivamus maximus turpis ut est viverra maximus id nec nisi. Nulla id interdum ipsum, a euismod nisl. Sed fringilla ullamcorper orci, sed dignissim justo volutpat ut. Maecenas tincidunt sollicitudin tincidunt. Ut enim dui, viverra ut porttitor ut, accumsan et velit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce egestas facilisis dolor, nec pretium turpis gravida nec. Pellentesque interdum sollicitudin sodales. Maecenas molestie ipsum justo, a ullamcorper nibh mattis eu. Sed maximus tempus turpis ut ornare. Aliquam vitae laoreet urna.

Mauris tincidunt dignissim aliquam. Morbi a lacinia nibh, a consequat massa. Aenean quis ligula porta velit fermentum congue. In et tortor odio. Sed a suscipit metus. Fusce in leo magna. Aenean at magna convallis neque gravida lacinia vel vitae justo. Integer viverra in eros ac egestas. Vivamus ipsum justo, auctor a nulla sed, rutrum gravida orci.

Sed neque ligula, feugiat sit amet lacinia id, porttitor nec justo. Maecenas commodo massa eu erat ornare, ac finibus magna luctus. In sed arcu feugiat, convallis ligula eget, viverra lacus. Vestibulum et enim non erat ultrices lobortis ac consectetur tortor. Aliquam egestas ipsum neque, at blandit lectus pharetra ut. Aenean egestas maximus urna, sed tempus lorem blandit ut. Integer vehicula quam leo, sed mollis ligula elementum at. Nam placerat a leo eu mattis. Ut eleifend scelerisque accumsan. Pellentesque venenatis consectetur lectus egestas porttitor. Sed convallis porttitor feugiat. Quisque suscipit orci ut gravida feugiat. Curabitur condimentum interdum dui, id gravida dolor lacinia at. Praesent non erat ac est interdum dignissim. Vestibulum feugiat nunc id ornare posuere.

Aenean at mollis neque. Cras pretium leo sit amet hendrerit congue. Vestibulum et felis nec lorem vestibulum condimentum in eu neque. Etiam a dapibus leo. Integer sed diam sit amet mi bibendum vestibulum id ut eros. Praesent laoreet mauris et leo varius convallis. Sed vulputate leo vel ex luctus posuere.

Maecenas in rutrum magna, vitae aliquam sem. Fusce lobortis finibus nibh. Fusce nec risus felis. Integer a sem ac ipsum ornare finibus. Donec lobortis dignissim neque, sit amet varius eros tristique id. Morbi consequat dui vitae odio lobortis pulvinar ac vitae massa. Nullam vitae cursus justo. Praesent lacinia velit et mi sagittis, id ullamcorper risus maximus. Nam nec commodo lectus.

Mauris id ullamcorper arcu, sed tincidunt enim. Suspendisse luctus fermentum sem, a viverra lectus sollicitudin in. Quisque mollis turpis leo, non aliquam felis accumsan id. Donec purus diam, porttitor a vulputate non, tincidunt a massa. Sed rhoncus lacinia gravida. Proin interdum, velit quis malesuada porttitor, leo nulla volutpat mauris, id fermentum nunc nulla pretium lacus. Fusce sit amet leo in eros pretium imperdiet eget at lorem. Aliquam nec rutrum nisl. Nunc varius finibus urna id pretium. Proin aliquet maximus nunc at viverra. Suspendisse varius accumsan cursus. Mauris ut sodales ipsum, ut scelerisque eros. Sed mi orci, mattis nec sodales eu, venenatis vel ante. Etiam tristique eget felis ut condimentum. Integer ut semper justo. Fusce aliquam laoreet libero id consequat.

Pellentesque accumsan pretium lorem vitae fermentum. Suspendisse eget sagittis nisi. Cras ac convallis lacus. Suspendisse neque enim, sodales id mauris eu, molestie feugiat turpis. Praesent condimentum feugiat viverra. Curabitur lacinia rutrum justo nec tincidunt. Aliquam erat volutpat. Sed quis molestie orci. Phasellus vitae dignissim dolor. Aliquam in bibendum nulla, sit amet tincidunt neque. Pellentesque dignissim diam ultricies, lobortis nisi eget, iaculis massa. Etiam rutrum eleifend erat, at ornare nisi venenatis eu. Pellentesque at fringilla dui. Nunc sapien tellus, finibus sed tellus in, elementum tempus orci. Donec pretium, velit quis dictum pharetra, sem diam pretium magna, eget tincidunt eros ex nec leo. Sed accumsan, nibh eu scelerisque vestibulum, tortor orci cursus erat, non volutpat elit purus fermentum orci.');
INSERT INTO MyBlog.BlogEntryContent (id, content) VALUES (8, 'albalb');
INSERT INTO MyBlog.BlogEntryContent (id, content) VALUES (9, 'are');
INSERT INTO MyBlog.BlogEntryContent (id, content) VALUES (10, 'bbb');
INSERT INTO MyBlog.BlogEntryContent (id, content) VALUES (11, 'some text here');
create table Roles
(
    id   int auto_increment
        primary key,
    name varchar(255) not null
);

INSERT INTO MyBlog.Roles (id, name) VALUES (1, 'Admin');
INSERT INTO MyBlog.Roles (id, name) VALUES (2, 'User');
create table Users
(
    id           int auto_increment
        primary key,
    emailAddress varchar(255) null,
    username     varchar(255) not null,
    password     varchar(255) null,
    displayName  varchar(255) null
);

INSERT INTO MyBlog.Users (id, emailAddress, username, password, displayName) VALUES (1, null, 'Chris', '123', 'Chris');
create table users_to_roles
(
    user_id int not null,
    role_id int not null,
    primary key (user_id, role_id)
);

INSERT INTO MyBlog.users_to_roles (user_id, role_id) VALUES (1, 1);